config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#index'

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
require 'google_books/client'

class Book < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :authors
  validates_presence_of :description
  validates_presence_of :image
  validates_presence_of :link
  validates :isbn_13, presence: true, uniqueness: true

  def self.search(query)
    GoogleBooks::Client.new.find_books(query)
  end

  def self.create_book(volumeInfo)
    @title = volumeInfo['title'] || ""
    @authors = volumeInfo['authors'] || []
    @description = volumeInfo['description'] || ""
    @image = volumeInfo.dig('imageLinks','thumbnail') || ""
    @link = volumeInfo['previewLink'] || ""
    @isbn_13 = volumeInfo['industryIdentifiers'].find{ |i|
        i['type'] == "ISBN_13"
      }['identifier'] rescue nil

    Book.create(
        title: @title,
        authors: @authors,
        description: @description,
        image: @image,
        link: @link,
        isbn_13: @isbn_13
      )
  end

  def print_authors
    self.authors.join(",\n") unless self.authors.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all.order(:title)
    if params[:query]
      @query = params[:query]
      @books = Book.search(@query)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
  <h3> Search results for: <%= @query %> </h3>
  <% if @books.blank? %>
    <h4> No books found. </h4>
  <% else %>
    <table class="table table-responsive">
      <thead>
        <tr>
          <th>Title</th>
          <th>Authors</th>
          <th>Description</th>
          <th>Image</th>
        </tr>
      </thead>
      <tbody>
        <% @books.first(10).each do |book| %>
          <tr>
            <td><%= link_to book.title, book.link, :target => "_blank" %></td>
            <td><%= book.print_authors %></td>
            <td><%= book.description %></td>
            <td><%= link_to image_tag(book.image), book.link, :target => "_blank" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Google Books</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="container">
    <body>
      <header class="navbar navbar-fixed-top navbar-inverse">
        <%= link_to "Google Books App", 'https://books.google.com/', id: "logo" %>
      </header>
      <div class="col-sm-3 col-md-3">
        <%= form_tag books_path, method: 'get', class: 'navbar-form', role: 'search' do %>
          <div class="input-group">
            <%= text_field_tag :query, params[:query], placeholder: "Search Books", class: "form-control"%>
            <div class="input-group-btn">
              <%= submit_tag "Search", class: 'btn btn-default' %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="container">

      <%= yield %>
      </div>
    </body>
  </div>
</html>